#nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  nginx
  template:
    metadata:
      labels:
        app:  nginx
    spec:
      containers:
      - name:  nginx
        image: localhost:5001/website_nginx #repo link
---
apiVersion: v1
kind: Service
metadata:
  name:  nginx
spec:
  type: LoadBalancer 
  selector:
    app:  nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80